# ===================================================================
# 🚀 AIVEN CLOUD DATABASE CONFIGURATION
# ===================================================================
# ⚠️ dhyan dein: yahan jdbc:mysql:// aur aakhir me port aur database ka naam hona zaroori hai!
server.port=${PORT:8081}
spring.datasource.url=jdbc:mysql://crm-mysql-live-ydasratkumar-fd37.e.aivencloud.com:25433/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_oDG0MF3_Dmw3yE72p0K
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===================================================================
# 📧 EMAIL CONFIGURATION (GMAIL SMTP EXAMPLE)
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ydasratkumar@gmail.com
spring.mail.password=kcoiycnvyoghhpwl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
