# Gmail SMTP Server Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# 1. Yahan aapka email sahi hai
spring.mail.username=ydasratkumar@gmail.com

# 2. Yahan aapka app password bhi bilkul sahi hai
spring.mail.password=kcoiycnvyoghhpwl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# MySQL Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/crm_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 🚀 REDIS CONFIGURATION
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Agar aapka Redis bina password ke chal raha hai toh ise khali chodein
spring.data.redis.password=